### ISSUE TITLE
[Suggestion] Add MAX_HEAT attribute

### ISSUE THREAD

**Issue by BitBlitObviMormon** [Sploder12/Potioncraft#3]
There is currently a way to make potions require a minimum heat level to brew but there is no documented way to make potions require a maximum heat level or a specific range of allowed heat levels. Some applications for MAX_HEAT could be to turn water into ice, or create modded liquids like liquid oxygen if on top of a very cold block. An application for combining MAX_HEAT with HAS_HEAT could be a boiled meat recipe or a potion with more delicate heat requirements. A campfire may cook them right, but a lava block might incinerate the ingredients or cause them to denature. Likewise a lack of heat would cause it to not cook.

**Comment by BitBlitObviMormon** [comment]
If these get implemented it might be worth renaming HAS_HEAT to something like MIN_HEAT to also remove ambiguity.

**Comment by Sploder12** [comment]
I like that idea, having a range of values opens up many cool possibilities. I will include this in v0.3.1, but since that may be in a while here is a workaround:

```json
...
{
    "id": "HAS_HEAT",
    "params": {
        "heat": (your max + 1)
    }
},
{
    "id": "INVERT_COND"
},
{
    "id": "HAS_HEAT",
    "quickfail": "PASS",
    "params": {
        "heat": (your min)
    }
},
...
```
Here is how I got this:
`HAS_HEAT(val) == (heat >= val) [for all positive integers val]` 

`(heat <= your max) && (heat >= your min)` ->
`!(heat > your max) && (heat >= your min)` ->
`!(heat >= your max + 1) && (heat >= your min)` ->
`!HAS_HEAT(your max + 1) && HAS_HEAT(your min)`

There are some limitations like 0 breaking it and different behavior for negative values.
